# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160419_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('last_login', models.DateTimeField(verbose_name='last login')),
                ('no_of_flights', models.IntegerField(default=0)),
                ('lives_in', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.City')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('last_login', models.DateTimeField(verbose_name='last login')),
                ('salary', models.IntegerField(default=0)),
                ('manager_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Staff')),
                ('works_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Airport')),
            ],
        ),
    ]
