# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20160419_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.Staff')),
                ('degree', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.Staff')),
                ('no_of_sold_tickets', models.IntegerField(default=0)),
            ],
        ),
    ]
