# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20160420_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('plane_id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('production_year', models.CharField(max_length=4)),
                ('max_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveSmallIntegerField()),
                ('seat_letter', models.CharField(max_length=1)),
                ('seat_class', models.CharField(max_length=20)),
                ('plane_id', models.ForeignKey(db_column='plane_id', on_delete=django.db.models.deletion.CASCADE, to='polls.Plane')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set([('seat_letter', 'seat_number', 'plane_id')]),
        ),
    ]
