# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20160420_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('staff_id', models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.Staff')),
                ('num_of_flights', models.IntegerField(default=0)),
                ('since', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hostess',
            fields=[
                ('staff_id', models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.Staff')),
                ('mother_language', models.CharField(max_length=30)),
                ('first_aid_ability', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('staff_id', models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='polls.Staff')),
                ('license_type', models.CharField(choices=[('national', 'only in country'), ('international', 'international flights')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='manager',
            name='degree',
            field=models.CharField(choices=[('full', 'full authorization'), ('partial', 'partial authorization')], max_length=100),
        ),
    ]
