# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20160420_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightLeg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_leg_code', models.CharField(max_length=7)),
                ('time', models.DateTimeField()),
                ('estimated_arr_time', models.DateTimeField()),
                ('no_of_available_seats', models.PositiveSmallIntegerField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('travel_distance', models.IntegerField()),
                ('price_for_economy', models.IntegerField()),
                ('price_for_business', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='airport',
            name='max_airplanes',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='no_of_airports',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crew',
            name='num_of_flights',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='no_of_flights',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plane',
            name='max_seats',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='salesman',
            name='no_of_sold_tickets',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flightleg',
            name='arrives',
            field=models.ForeignKey(db_column='arrives', on_delete=django.db.models.deletion.CASCADE, related_name='landing_flights', to='polls.Airport'),
        ),
        migrations.AddField(
            model_name='flightleg',
            name='departs',
            field=models.ForeignKey(db_column='departs', on_delete=django.db.models.deletion.CASCADE, related_name='departing_flights', to='polls.Airport'),
        ),
        migrations.AddField(
            model_name='flightleg',
            name='plane_id',
            field=models.ForeignKey(db_column='plane_id', on_delete=django.db.models.deletion.CASCADE, to='polls.Plane'),
        ),
        migrations.AddField(
            model_name='crew',
            name='participates',
            field=models.ManyToManyField(to='polls.FlightLeg'),
        ),
        migrations.AlterUniqueTogether(
            name='flightleg',
            unique_together=set([('flight_leg_code', 'time')]),
        ),
    ]
