# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20160420_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('extra_luggage', models.BooleanField(default=False)),
                ('reservation_time', models.DateTimeField(auto_now_add=True)),
                ('cust_id', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.CASCADE, to='polls.Customer')),
                ('fligt_leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.FlightLeg')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Seat')),
                ('sold_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Salesman')),
            ],
        ),
    ]
